sudo: true
language: node_js
dist: trusty
node_js:
  - 'stable'

# Set up a virtual screen for Chrome and Firefox.
before_script:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
